### ISSUE TITLE
Request to Contribute New Code and Add Hacktoberfest2023 Tag

### ISSUE THREAD

**Issue by ShaswatShrivas** [KarthikGanapaR/Hacktoberfest-23#6]
Hello,

I'm interested in contributing to this repository by adding new code that is not currently present. I would also like to request that you add the "hacktoberfest2023" tag to this repository to encourage participation in the upcoming Hacktoberfest event.

Contributing to open source projects is an excellent way to upgrade my skills and collaborate with the community. I believe this will be a valuable addition to the project and would love the opportunity to work on it.

Could you please consider assigning this issue to me? I'm excited to get started and make a positive impact on the project.

Thank you!

**Comment by Shubhgupta-coder** [comment]
pls assign this issue to me

**Comment by KarthikGanapaR** [comment]
@Shubhgupta-coder I have assigned this issue you can work on it

**Comment by Shubhgupta-coder** [comment]
Sir, please check I have added quick sort algo in C++.

**Comment by ShaswatShrivas** [comment]
Can you close this issue please.
I think, it is making the pr not valid for validation in hacktoberfest @KarthikGanapaR
